# Generated by Django 4.1.4 on 2022-12-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='input_files/')),
                ('output_file', models.FileField(upload_to='output_files/')),
            ],
        ),
    ]
