# Generated by Django 4.1.4 on 2022-12-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileoperations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.CharField(max_length=100)),
                ('output_file', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=5)),
                ('is_zipped', models.BooleanField(default=False)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('key_file', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
